export namespace PersonalInfoTypes {
    export namespace UI {
        export interface IPersonalInfoContainer {
            id: string;
        }
        export interface IPersonalInfo extends Data.Person {
            isSpecial: boolean;
        }
    }

    export namespace Data {
        //This will come from the schema generated by Apollo
        export interface Person {
            id: string;
            name: string
            age: number;
            gener: 'male' | 'female'
        }
    }

    export namespace Store {
        export type People = {string: {isSpecial: boolean}}

        export interface State {
            people: People;
        } 
    }

    export namespace Utils {
        export type GetIsSpecial = (state: Store.State, id: string) => boolean;
    }
}


